name: "Multi-event-pipeline/Workflow"

on:
  push:
    branches:
      - master
      - test

  pull_request:
    branches:
      - master
    types:
      - closed

  workflow_dispatch: # Manual trigger

jobs:
  on-push: # Job 1
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Running On Master/test push"
        run: echo "This is a master push event"

  on-pull-request: # Job 2
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Running On Master pull request"
        run: echo "This is a master pull request event"

  on-pull-request-closed: # Job for pull request closed event
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "Running On Master pull request closed"
        run: echo "Running on pull request closed event"

  on-workflow-dispatch: # Job 3
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Running On Manual trigger"
        run: echo "Running on workflow_dispatch event"
