name:  "Muiltievent-pipline/Workflow"

on:
    # Trigger the workflow on push or pull request,
    push:
        branches:
            - master
            - test
    
    pull_request:
        branches:
            - master
            
    workflow_dispatch: #manual trigger
        


jobs:
    on-push: #job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Runing On Master/test push"
              run: echo "This is a master push event"

    on-pull-request: #job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Runing On Master pull request"
              run: echo "This is a master pull request event"

    