name:  "Muiltievent-pipline/Workflow"

on:
    push:
        branches:
            - master
            - test

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Runing On Master push"
              run: echo "This is a master push event"